name: Deploy to registry and Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          install_only: true

      - name: Clean
        run: |
          rm -rf .cr-release-packages
          mkdir -p .cr-release-packages
          rm -rf .cr-index
          mkdir -p .cr-index
          rm -rf .ollama-helm
          mkdir -p .ollama-helm

      - name: Copy Ollama chart
        run: |
          cp -r templates .ollama-helm/
          cp Chart.yaml .ollama-helm/
          cp LICENSE .ollama-helm/
          cp values.yaml .ollama-helm/
          cp .helmignore .ollama-helm/
          cp README.md .ollama-helm/

      - name: Package chart
        run: cr package .

      - name: Upload chart
        run: cr upload --owner otwld --git-repo ollama-helm --generate-release-notes -c "$(git rev-parse HEAD)"
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Upload chart index
        run: cr index --owner otwld --git-repo ollama-helm --push
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # Migration to OTWLD helm charts repository
      - name: Push to central helm-charts repo
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.HELM_CHARTS_REPO_TOKEN }}
        with:
          source-directory: ".ollama-helm/"
          target-directory: "charts/ollama"
          destination-github-username: ${{ github.repository_owner }}
          destination-repository-name: "helm-charts"
          user-email: "$GITHUB_ACTOR@users.noreply.github.com"
          target-branch: main